id: AC86E4BB5
base_file: fE244.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:09:41.491903
  last_modified_at: 2022-06-11 13:09:41.491911
